#! /bin/bash

test -f /usr/bin/liquidshell && {
  sed -i \
    -e 's/translucent_windows=true/translucent_windows=false/' \
    /usr/share/Kvantum/KvNitruxDark/KvNitruxDark.kvconfig

  sed -i \
    -e 's/translucent_windows=true/translucent_windows=false/'\
    /usr/share/Kvantum/KvNitrux/KvNitrux.kvconfig

	} || {
  continue
	}

exit